care_backend/affiliate_business/urls.py
from django.urls import path
from affiliate_business.views import BusinessListView,BusinessCreateView,BusinessDetailView,BusinessUpdateView,BusinessDeleteView, load_cities

urlpatterns = [
  path('business/', BusinessListView.as_view(), name="negocio"),
  path('business/create', BusinessCreateView.as_view(), name="crear_negocio"),
  path('business/<int:pk>',BusinessDetailView.as_view(), name="detalle_negocio"),
  path('business/update/<int:pk>',BusinessUpdateView.as_view(), name="actualizar_negocio"),
  path('business/delete/<int:pk>',BusinessDeleteView.as_view(), name="eliminar_negocio"),
  path('ajax/load-cities/',load_cities, name='ajax_load_cities'),
]

care_backend/care_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from api import views as my_view
from api.router import router
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/token/', my_view.TokenView.as_view()),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="user/password_reset_confirm.html"),
        name='password_reset_confirm'),
    path('api/rest-auth/', include('rest_auth.urls')),
    #Paths del core
    path('', include('core.urls')),
    #Paths del affiliate_business
    path('', include('affiliate_business.urls')),
    #Paths del vehicle
    path('', include('vehicle.urls')),
    #Paths del business_owner
    path('', include('business_owner.urls')),
    #Paths del user
    path('', include('user.urls')),
    #Paths del advertisement
    path('', include('advertisement.urls')),
    #path('upload/', my_view.PPUploadView.as_view()),
    #Paths del loggin
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

care_backend/core/urls.py
from django.urls import path
from .views import NavPageView, HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('Principal/', NavPageView.as_view(), name="principal"),

]

care_backend/affiliate_business/models.py
from django.db import models
from api.models import City, Province, Affiliate_business, User

care_backend/api/models.py
from django.db import models
from model_utils.fields import StatusField
from model_utils import Choices
from django.utils import timezone
from api.manager import UserManager
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, \
                                        PermissionsMixin
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _

class User(AbstractBaseUser, PermissionsMixin):
	'''Custom User Model that supports using email instead of username'''
	email=models.EmailField(max_length=255, unique=True)
	name=models.CharField(max_length=255)
	lastname=models.CharField(max_length=255)
	phone_number=models.CharField(max_length=10)
	is_active=models.BooleanField(default=True, blank=True)
	is_staff=models.BooleanField(default=False, blank=True,verbose_name="Administrador")
	is_business_owner=models.BooleanField(default=False, blank=True,verbose_name="Dueño de Negocio")
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
	#add_by = models.ForeignKey(Affiliate_business, on_delete=models.CASCADE, null=True, blank=True)
	
	objects=UserManager()
	USERNAME_FIELD='email'

	def __str__(self):
		return self.name+' '+self.lastname

class ProfilePicture(models.Model):
	creation_date = models.DateTimeField(auto_now_add=True, editable=False)
	modified_date = models.DateTimeField(auto_now=True)
	file = models.CharField(max_length=255)	
	user = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.user

class Province(models.Model):
	province = models.CharField(max_length=254)

	def __str__(self):
		return self.province

class City(models.Model):
	city = models.CharField(max_length=254)
	province = models.ForeignKey(Province, on_delete=models.CASCADE)
	
	def __str__(self):
		return self.city

class Brand(models.Model):
	brand = models.CharField(max_length=254)

	def __str__(self):
		return self.brand

class Model(models.Model):
	model = models.CharField(max_length=254)
	brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

	def __str__(self):
		return self.model

"""class EmployeeAccount(models.Model):
	id_number = models.CharField(max_length=10, unique=True)
	name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	dob = models.DateField()
	is_admin = models.BooleanField(default=False)
	profession = models.CharField(max_length=50, default="")
	account = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
"""
class Affiliate_business(models.Model):
	ruc = models.CharField(max_length=13, unique=True)
	business_name = models.CharField(max_length=255)
	description = models.TextField(max_length=255,null=True, blank=True)
	business_phone = models.CharField(max_length=13)
	province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True)
	city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
	legal_representative_name = models.CharField(max_length=255)
	legal_representative_lastname = models.CharField(max_length=255)
	business_owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	address = models.CharField(max_length=255)
	""" contact_name = models.CharField(max_length=255)
	contact_lastname = models.CharField(max_length=255)
	contact_work_position = models.CharField(max_length=255)
	contact_phone_number = models.CharField(max_length=13) """
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
	lon = models.DecimalField(max_digits=22, decimal_places=16, null=True, blank=True)
	lat = models.DecimalField(max_digits=22, decimal_places=16, null=True, blank=True)

	def __str__(self):
		return self.business_name

class Affiliate_business_Clients(models.Model):
	client =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	business = models.ForeignKey(Affiliate_business, on_delete=models.SET_NULL, null=True)
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación",null=True,blank=True)
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición",null=True,blank=True)

class Vehicle(models.Model):
	YEAR_CHOICES = [(y,y) for y in range(1960, (datetime.date.today().year)+2)]
	owner = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)
	brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
	model = models.ForeignKey(Model, on_delete=models.SET_NULL, null=True)
	plate = models.CharField(max_length=10)
	color = models.CharField(max_length=20)
	""" engine = models.CharField(max_length=25,default="") """
	year = models.IntegerField(choices=YEAR_CHOICES,default=datetime.datetime.now().year,)
	description = models.TextField(max_length=255, default="")
	km = models.CharField(max_length=20)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
	imageURL = models.CharField(max_length=500, null=True, blank=True)
	registration = models.DateField(null=True, blank=True)

	def __str__(self):
		return self.plate

class Maintenance_item(models.Model):
	item = models.CharField(max_length=255)
	itype = models.CharField(max_length=255,blank=True,null=True)

class Maintenance(models.Model):
	brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
	model = models.ForeignKey(Model, on_delete=models.SET_NULL, null=True)
	m_name = models.ForeignKey(Maintenance_item, on_delete=models.SET_NULL, null=True)
	km = models.CharField(max_length=20,null=True)
	month = models.CharField(max_length=3,null=True)
	km_to_inspect = models.CharField(max_length=20,null=True)
	is_change = models.BooleanField(default=False)
	is_maintenance = models.BooleanField(default=False)
	description = models.TextField(max_length=255, default="")

	def __str__(self):
		return self.m_name

""" class Maintenance_Type(models.Model):
	mt_name = models.CharField(max_length=255, primary_key=True)
	maintenance = models.ForeignKey(Maintenance, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.mt_name """

class MaintenanceDetails(models.Model):
	item = models.ForeignKey(Maintenance_item, null=True, blank=True, on_delete = models.CASCADE)
	#maintenance = models.ForeignKey(Maintenance, on_delete = models.CASCADE)
	#m_type = models.ForeignKey(Maintenance_Type, on_delete = models.CASCADE)
	vehicle = models.ForeignKey(Vehicle, on_delete = models.CASCADE, null=True)
	local = models.ForeignKey(Affiliate_business, null=True, blank=True, on_delete = models.CASCADE)
	date =  models.DateTimeField(default=timezone.now)
	price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	km = models.CharField(max_length=20, null=True)
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación",blank=True,null=True)


class Travel(models.Model):
	vehicle = models.ForeignKey(Vehicle, null=True, blank=True, on_delete = models.CASCADE)
	description = models.TextField(max_length=255, default="")
	start_place = models.CharField(max_length=255)
	end_place = models.CharField(max_length=255)
	start_km = models.PositiveIntegerField(blank=True, null=True)
	final_km = models.PositiveIntegerField(blank=True, null=True)
	start_time = models.TimeField()
	end_time = models.TimeField(blank=True, null=True)	
	is_active = models.BooleanField(default=True)
	no_passanger = models.PositiveSmallIntegerField(blank=True, null=True, default=1)

class Expense(models.Model):
	#STATUS = Choices('Gasolina', 'Alimentos', 'Peaje', 'Hospedaje', 'Otros')
	#type_ex = StatusField()
	expense_value = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	payment_method = models.CharField(max_length=255)
	date = models.DateTimeField(default=timezone.now)
	address = models.CharField(max_length=255, blank=True)
	name = models.CharField(max_length=255, blank=True)

class Advertisement(models.Model):
	affiliate_business = models.ForeignKey(Affiliate_business, null=True, blank=True, on_delete = models.CASCADE)
	description = models.CharField(max_length=255)
	banner = models.CharField(max_length=500, null=True, blank=True)

class Suggestion(models.Model):
    user_suggestion = models.ForeignKey(User, null=True, blank=True, on_delete = models.CASCADE)
    title = models.CharField(max_length=150,null=True, blank=True)
    comment_suggestion = models.CharField(max_length=255,null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="Fecha de creación")

class Announcement(models.Model):
	affiliate_business = models.ForeignKey(Affiliate_business, null=True, blank=True, on_delete = models.CASCADE)
	title = models.CharField(max_length=150,null=True, blank=True)
	description = models.CharField(max_length=255)	

class Notifications(models.Model):
	announcement = models.ForeignKey(Announcement, on_delete = models.CASCADE, null=True, blank=True)
	user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)

class UDevice(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)
	device_id = models.CharField(max_length=150, null=True, default=None)

class Fine(models.Model):
	value = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	date = models.DateTimeField(default=timezone.now)
	reason = models.CharField(max_length=255, blank=True)
	address = models.CharField(max_length=255, blank=True)
	agency = models.CharField(max_length=255, blank=True)
	agent = models.CharField(max_length=255, blank=True)

care_backend/affiliate_business/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from affiliate_business.models import City, Province, Affiliate_business
from affiliate_business.forms import BusinessUpdateForm, BusinessCreateForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from bootstrap_modal_forms.generic import (BSModalCreateView,
                                           BSModalUpdateView,
                                           BSModalReadView,
                                           BSModalDeleteView)
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from api.decorators import admin_required
# Create your views here.


# BUSINESS
@method_decorator([login_required,admin_required], name='dispatch')
class BusinessListView(ListView):
  model = Affiliate_business
  template_name = 'affiliate_business/business_list.html'
  paginate_by = 10

@method_decorator([login_required,admin_required], name='dispatch')
class BusinessCreateView(CreateView):
  model = Affiliate_business
  template_name = 'affiliate_business/business_create.html'
  form_class = BusinessCreateForm
  #success_url = reverse_lazy('negocio')
  def form_valid(self,form):
    self.object = form.save(commit=False)
    self.object.save()
    return HttpResponseRedirect(reverse_lazy('negocio'))

@method_decorator([login_required,admin_required], name='dispatch')
class BusinessDetailView(BSModalReadView):
  model = Affiliate_business  
  template_name = 'affiliate_business/business_detail.html'

@method_decorator([login_required,admin_required], name='dispatch')
class BusinessUpdateView(BSModalUpdateView):
  model = Affiliate_business
  template_name = 'affiliate_business/business_update.html'
  form_class = BusinessUpdateForm
  success_message = 'Éxito: Negocio actualizado.'
  success_url = reverse_lazy('negocio')

@method_decorator([login_required,admin_required], name='dispatch')
class BusinessDeleteView(BSModalDeleteView):
    model = Affiliate_business
    template_name = 'affiliate_business/business_delete.html'
    success_message = 'Éxito: Negocio eliminado.'
    success_url = reverse_lazy('negocio')

#Functions
def load_cities(request):
    province_id = request.GET.get('province')
    cities = City.objects.filter(province_id=province_id).order_by('city')
    return render(request, 'affiliate_business/city_dropdown_list_options.html', {'cities': cities})

care_backend/affiliate_business/templates/affiliate_business/business_create.html
{% extends 'core/navs.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content1 %}
{% comment %} {% include 'resource/includes/resource_menu.html' %} {% endcomment %}

{% comment %} {% load i18n %}
        
{% block head %}
{{ wizard.form.media }}
{% endblock %} {% endcomment %}

<div class="container-fluid" style="background-color: #FFFFFF !important;">
  <div class="container">
    <div class="justify-content-center">
      
      <form action="" id="businessForm" enctype="multipart/form-data" method="post" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
          {% csrf_token %}
          
          <div class="pt-4 pb-4">
            <label style="font-size: 22px;" class="text-secondary">REGISTRAR NUEVO NEGOCIO</label>
          </div>
          {% comment %} <div class="{% if form.non_field_errors %}invalid{% endif %} ">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
          </div> {% endcomment %}
          
          <div class="col-md">
            <div class="row">
              <div class='col-md-6 pt-2'>

                <label class="text-secondary pl-2" style="font-size: 14px;">RUC</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.ruc placeholder=field.label %} 
                  </div>
                  <div class="{% if field.errors %} has-error{% endif %}">
                      <p class="invalid-feedback">{{ form.errors.ruc }}</p>
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Nombre Negocio</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.business_name placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Teléfono Negocio</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.business_phone  placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Provincia</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.province placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Ciudad</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.city placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 13px;">Dirección</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                      {% render_field form.address placeholder=field.label %}
                  </div>
                </div>
              </div>

              <div class='col-md-6 pt-2'>
                <label class="text-secondary pl-2" style="font-size: 14px;">Nombre Representante Legal</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.legal_representative_name  placeholder=field.label %} 
                  </div>
                  <div class="{% if field.errors %} has-error{% endif %}">
                      <p class="invalid-feedback">{{ form.errors.legal_representative_name }}</p>
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Apellido Representante Legal</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.legal_representative_lastname  placeholder=field.label %} 
                  </div>
                  <div class="{% if field.errors %} has-error{% endif %}">
                      <p class="invalid-feedback">{{ form.errors.legal_representative_lastname }}</p>
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Dueño de Negocio</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.business_owner  placeholder=field.label %} 
                  </div>
                  <div class="{% if field.errors %} has-error{% endif %}">
                      <p class="invalid-feedback">{{ form.errors.business_owner }}</p>
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Descripción</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.description  placeholder=field.label %} 
                  </div>
                </div>
                
              </div>
            </div>
          </div>
          <div class="col-md-3 pl-0 pb-3 pt-5" style="margin-left: 300px;">
            <div class="pl-0">
              <input type="submit" class="btn btn-outline-light btn-block" style="background-color: #b24f37;" value="Guardar" />
            </div>
          </div>
        </form> 

    </div>
  </div>
</div>


<script>
  $("#id_province").change(function () {
    var url = $("#businessForm").attr("data-cities-url");  // get the url of the `load_cities` view
    var provinceId = $(this).val();  // get the selected country ID from the HTML input

    $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
      data: {
        'province': provinceId       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
        $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
      }
    });
  });
</script>
{% endblock %}

care_backend/affiliate_business/templates/affiliate_business/business_delete.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Eliminar Negocio</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">¿Seguro deseas eliminar el negocio 
      <strong>{{ object.business_name }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="delete-btn btn btn-danger">Eliminar</button>
  </div>

</form>

care_backend/affiliate_business/templates/affiliate_business/business_detail.html
{% load widget_tweaks %}
{% load static %}

<div class="modal-header">
  <h3 class="modal-title">Negocio Afiliado</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <div class="mt-4 mb-4 ml-4 mr-4">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-auto">
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">RUC:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.ruc }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Nombre Negocio:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label  style="font-size: 14px;">{{ object.business_name }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" class="text-secondary" style="font-size: 14px;">Teléfono Negocio:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.business_phone }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Ciudad:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.city }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Dirección:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;"> {{ object.address }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Nombre Representante Legal:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label  style="font-size: 14px;">{{ object.legal_representative_name }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Apellido Representante Legal:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.legal_representative_lastname }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Descripción:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.description }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Fecha de creación:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label  style="font-size: 14px;">{{ object.created }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Fecha de actualización:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.updated }}</label>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

care_backend/affiliate_business/templates/affiliate_business/business_list.html
{% extends 'core/navs.html' %}
{% load static %}

{% block content1 %}
  {% comment %} {% include 'resource/includes/resource_menu.html' %} {% endcomment %}

  <div class="container-fluid" style="background-color: #FFFFFF !important;">
    <div class="container">
      <div class="justify-content-center">


        <!--MODAL FADE-->
        {% include 'affiliate_business/modal.html' %}
        <!--END MODAL FADE-->

        <div class="pb-4 pt-4">
          <div class="text-right">
              <a class="navbar-brand ml-4 font-weight-bold  text-info" href="{% url 'crear_negocio' %}" style="font-size: 12px;">REGISTRAR NUEVO NEGOCIO</a>
          </div>
          <table class="table table-borderless">
            {% for business in object_list|dictsort:"business_name" %}

              {% if forloop.first %}
                <thead>
                  <tr class="text-center">
                    <th scope="col"><p class="text-secondary" style="font-size: 12px;">Ruc</p></th>
                    <th scope="col"><p class="text-secondary" style="font-size: 12px;">Nombre del negocio</p></th>
                    <th scope="col"><p class="text-secondary" style="font-size: 12px;">Ciudad</p></th>
                    <th scope="col"><p class="text-secondary" style="font-size: 12px;">Descripción</p></th>
                    <th scope="col"><p class="text-secondary" style="font-size: 12px;">Dirección</p></th>
                  </tr>
                </thead>
              {% endif %}
              
              <tbody>
                <tr scope="row" class="center-block text-center border rounded-pill pt-3 pb-3">
                  <td><p class="mt-3 font-weight-bold text-secondary" style="font-size: 15px;">{{business.ruc}}</p></td>
                  <td><p class="mt-3 font-weight-bold text-secondary" style="font-size: 15px;">{{business.business_name}}</p></td>
                  <td><p class="mt-3 font-weight-bold text-secondary" style="font-size: 15px;">{{business.city}}</p></td>
                  <td><p class="mt-3 font-weight-bold text-secondary" style="font-size: 15px;">{{business.description}}</p></td>
                  <td><p class="mt-3 font-weight-bold text-secondary" style="font-size: 15px;">{{business.address}}</p></td>
                  <td class="pt-0"><button type="button" class="business_detail btn mt-4 btn-sm text-white" 
                  style="background-color: #b24f37;" data-id="{% url 'detalle_negocio' business.pk %}"><span class="fa fa-eye"></span></button></td>
                  <td class="pt-0"><button type="button" class="business_update btn mt-4 btn-sm btn-primary" data-id="{% url 'actualizar_negocio' business.pk %}">
                    <span class="fa fa-pencil"></span>
                  </button></td>
                  <td class="pt-0"><button type="button" class="business_delete btn mt-4 btn-sm btn-danger" data-id="{% url 'eliminar_negocio' business.pk %}">
                    <span class="fa fa-trash"></span>
                  </button></td>
                </tr>
              </tbody>
              {% empty %}
                <div class="row mt-3">
                  <h4>No hay datos que presentar</h4>
                </div>
            {% endfor %}
          </table>
        </div>

        <!-- Menú de paginación -->
        {% if is_paginated %}
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                </li>
              {% endif %}
              {% for i in paginator.page_range %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        {% endif %}

        <!-- Contenido extra -->
        <div class="pb-5">
        </div>
        <div class="pb-5">
        </div>
        <div class="pb-5">
        </div>
        <div class="pb-5">
        </div>
        
      </div>
    </div>
  </div>

{% endblock %}

care_backend/affiliate_business/templates/affiliate_business/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.city }}</option>
{% endfor %}