care_backend/care_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from api import views as my_view
from api.router import router
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/token/', my_view.TokenView.as_view()),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="user/password_reset_confirm.html"),
        name='password_reset_confirm'),
    path('api/rest-auth/', include('rest_auth.urls')),
    #Paths del core
    path('', include('core.urls')),
    #Paths del affiliate_business
    path('', include('affiliate_business.urls')),
    #Paths del vehicle
    path('', include('vehicle.urls')),
    #Paths del business_owner
    path('', include('business_owner.urls')),
    #Paths del user
    path('', include('user.urls')),
    #Paths del advertisement
    path('', include('advertisement.urls')),
    #path('upload/', my_view.PPUploadView.as_view()),
    #Paths del loggin
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

care_backend/core/urls.py
from django.urls import path
from .views import NavPageView, HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('Principal/', NavPageView.as_view(), name="principal"),

]

care_backend/vehicle/urls.py
from django.urls import path
from vehicle.views import VehicleListView,VehicleCreateView,VehicleDetailView,VehicleUpdateView,VehicleDeleteView,load_models

urlpatterns = [
  path('vehicle/', VehicleListView.as_view(), name="vehiculo"),
  path('vehicle/create', VehicleCreateView.as_view(), name="crear_vehiculo"),
  path('vehicle/<int:pk>',VehicleDetailView.as_view(), name="detalle_vehiculo"),
  path('vehicle/update/<int:pk>',VehicleUpdateView.as_view(), name="actualizar_vehiculo"),
  path('vehicle/delete/<int:pk>',VehicleDeleteView.as_view(), name="eliminar_vehiculo"),
  path('ajax/load-models/',load_models, name='ajax_load_models'),
]

care_backend/api/models.py
from django.db import models
from model_utils.fields import StatusField
from model_utils import Choices
from django.utils import timezone
from api.manager import UserManager
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, \
                                        PermissionsMixin
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _

class User(AbstractBaseUser, PermissionsMixin):
	'''Custom User Model that supports using email instead of username'''
	email=models.EmailField(max_length=255, unique=True)
	name=models.CharField(max_length=255)
	lastname=models.CharField(max_length=255)
	phone_number=models.CharField(max_length=10)
	is_active=models.BooleanField(default=True, blank=True)
	is_staff=models.BooleanField(default=False, blank=True,verbose_name="Administrador")
	is_business_owner=models.BooleanField(default=False, blank=True,verbose_name="Dueño de Negocio")
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
	#add_by = models.ForeignKey(Affiliate_business, on_delete=models.CASCADE, null=True, blank=True)
	
	objects=UserManager()
	USERNAME_FIELD='email'

	def __str__(self):
		return self.name+' '+self.lastname

class ProfilePicture(models.Model):
	creation_date = models.DateTimeField(auto_now_add=True, editable=False)
	modified_date = models.DateTimeField(auto_now=True)
	file = models.CharField(max_length=255)	
	user = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.user

class Province(models.Model):
	province = models.CharField(max_length=254)

	def __str__(self):
		return self.province

class City(models.Model):
	city = models.CharField(max_length=254)
	province = models.ForeignKey(Province, on_delete=models.CASCADE)
	
	def __str__(self):
		return self.city

class Brand(models.Model):
	brand = models.CharField(max_length=254)

	def __str__(self):
		return self.brand

class Model(models.Model):
	model = models.CharField(max_length=254)
	brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

	def __str__(self):
		return self.model

"""class EmployeeAccount(models.Model):
	id_number = models.CharField(max_length=10, unique=True)
	name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	dob = models.DateField()
	is_admin = models.BooleanField(default=False)
	profession = models.CharField(max_length=50, default="")
	account = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
"""
class Affiliate_business(models.Model):
	ruc = models.CharField(max_length=13, unique=True)
	business_name = models.CharField(max_length=255)
	description = models.TextField(max_length=255,null=True, blank=True)
	business_phone = models.CharField(max_length=13)
	province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True)
	city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
	legal_representative_name = models.CharField(max_length=255)
	legal_representative_lastname = models.CharField(max_length=255)
	business_owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	address = models.CharField(max_length=255)
	""" contact_name = models.CharField(max_length=255)
	contact_lastname = models.CharField(max_length=255)
	contact_work_position = models.CharField(max_length=255)
	contact_phone_number = models.CharField(max_length=13) """
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
	lon = models.DecimalField(max_digits=22, decimal_places=16, null=True, blank=True)
	lat = models.DecimalField(max_digits=22, decimal_places=16, null=True, blank=True)

	def __str__(self):
		return self.business_name

class Affiliate_business_Clients(models.Model):
	client =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	business = models.ForeignKey(Affiliate_business, on_delete=models.SET_NULL, null=True)
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación",null=True,blank=True)
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición",null=True,blank=True)

class Vehicle(models.Model):
	YEAR_CHOICES = [(y,y) for y in range(1960, (datetime.date.today().year)+2)]
	owner = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)
	brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
	model = models.ForeignKey(Model, on_delete=models.SET_NULL, null=True)
	plate = models.CharField(max_length=10)
	color = models.CharField(max_length=20)
	""" engine = models.CharField(max_length=25,default="") """
	year = models.IntegerField(choices=YEAR_CHOICES,default=datetime.datetime.now().year,)
	description = models.TextField(max_length=255, default="")
	km = models.CharField(max_length=20)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
	updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
	imageURL = models.CharField(max_length=500, null=True, blank=True)
	registration = models.DateField(null=True, blank=True)

	def __str__(self):
		return self.plate

class Maintenance_item(models.Model):
	item = models.CharField(max_length=255)
	itype = models.CharField(max_length=255,blank=True,null=True)

class Maintenance(models.Model):
	brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
	model = models.ForeignKey(Model, on_delete=models.SET_NULL, null=True)
	m_name = models.ForeignKey(Maintenance_item, on_delete=models.SET_NULL, null=True)
	km = models.CharField(max_length=20,null=True)
	month = models.CharField(max_length=3,null=True)
	km_to_inspect = models.CharField(max_length=20,null=True)
	is_change = models.BooleanField(default=False)
	is_maintenance = models.BooleanField(default=False)
	description = models.TextField(max_length=255, default="")

	def __str__(self):
		return self.m_name

""" class Maintenance_Type(models.Model):
	mt_name = models.CharField(max_length=255, primary_key=True)
	maintenance = models.ForeignKey(Maintenance, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.mt_name """

class MaintenanceDetails(models.Model):
	item = models.ForeignKey(Maintenance_item, null=True, blank=True, on_delete = models.CASCADE)
	#maintenance = models.ForeignKey(Maintenance, on_delete = models.CASCADE)
	#m_type = models.ForeignKey(Maintenance_Type, on_delete = models.CASCADE)
	vehicle = models.ForeignKey(Vehicle, on_delete = models.CASCADE, null=True)
	local = models.ForeignKey(Affiliate_business, null=True, blank=True, on_delete = models.CASCADE)
	date =  models.DateTimeField(default=timezone.now)
	price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	km = models.CharField(max_length=20, null=True)
	created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación",blank=True,null=True)


class Travel(models.Model):
	vehicle = models.ForeignKey(Vehicle, null=True, blank=True, on_delete = models.CASCADE)
	description = models.TextField(max_length=255, default="")
	start_place = models.CharField(max_length=255)
	end_place = models.CharField(max_length=255)
	start_km = models.PositiveIntegerField(blank=True, null=True)
	final_km = models.PositiveIntegerField(blank=True, null=True)
	start_time = models.TimeField()
	end_time = models.TimeField(blank=True, null=True)	
	is_active = models.BooleanField(default=True)
	no_passanger = models.PositiveSmallIntegerField(blank=True, null=True, default=1)

class Expense(models.Model):
	#STATUS = Choices('Gasolina', 'Alimentos', 'Peaje', 'Hospedaje', 'Otros')
	#type_ex = StatusField()
	expense_value = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	payment_method = models.CharField(max_length=255)
	date = models.DateTimeField(default=timezone.now)
	address = models.CharField(max_length=255, blank=True)
	name = models.CharField(max_length=255, blank=True)

class Advertisement(models.Model):
	affiliate_business = models.ForeignKey(Affiliate_business, null=True, blank=True, on_delete = models.CASCADE)
	description = models.CharField(max_length=255)
	banner = models.CharField(max_length=500, null=True, blank=True)

class Suggestion(models.Model):
    user_suggestion = models.ForeignKey(User, null=True, blank=True, on_delete = models.CASCADE)
    title = models.CharField(max_length=150,null=True, blank=True)
    comment_suggestion = models.CharField(max_length=255,null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="Fecha de creación")

class Announcement(models.Model):
	affiliate_business = models.ForeignKey(Affiliate_business, null=True, blank=True, on_delete = models.CASCADE)
	title = models.CharField(max_length=150,null=True, blank=True)
	description = models.CharField(max_length=255)	

class Notifications(models.Model):
	announcement = models.ForeignKey(Announcement, on_delete = models.CASCADE, null=True, blank=True)
	user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)

class UDevice(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)
	device_id = models.CharField(max_length=150, null=True, default=None)

class Fine(models.Model):
	value = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	date = models.DateTimeField(default=timezone.now)
	reason = models.CharField(max_length=255, blank=True)
	address = models.CharField(max_length=255, blank=True)
	agency = models.CharField(max_length=255, blank=True)
	agent = models.CharField(max_length=255, blank=True)

care_backend/vehicle/models.py
from django.db import models
from api.models import Vehicle, Brand, Model

# Create your models here.

care_backend/vehicle/forms.py
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from bootstrap_modal_forms.forms import BSModalForm
from vehicle.models import Vehicle, Brand, Model
from django.core import validators
import datetime


class VehicleUpdateForm(BSModalForm):
  class Meta:
      model = Vehicle
      fields = '__all__'
  def clean_plate(self):
    plate = self.cleaned_data['plate']
    val = validators.RegexValidator(regex='^[A-Z]{3}-[0-9]{4}$', message ="Placa no valida! intente nuevamente")
    val(plate)
    return plate

def year_choices():
  return [(r,r) for r in range(1984, datetime.date.today().year+1)]


def current_year():
    return datetime.date.today().year

class VehicleCreateForm(forms.ModelForm):
  class Meta:
    model = Vehicle
    fields = '__all__'
    widgets = {
      'owner': forms.Select(attrs={'class':'form-control'}),
      'brand': forms.Select(attrs={'class':'form-control'}),
      'model': forms.Select(attrs={'class':'form-control'}),
      'plate': forms.TextInput(attrs={'class':'form-control'}),
      'color': forms.TextInput(attrs={'class':'form-control'}),
      'description': forms.Textarea(attrs={'class':'form-control','rows':5}),
      'km': forms.TextInput(attrs={'class':'form-control'}),
    }
  
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['model'].queryset = Model.objects.none()

    if 'brand' in self.data:
      try:
        brand_id = int(self.data.get('brand'))
        self.fields['model'].queryset = Model.objects.filter(brand_id=brand_id).order_by('model')
      except (ValueError, TypeError):
        pass  # invalid input from the client; ignore and fallback to empty City queryset
    elif self.instance.pk:
      self.fields['model'].queryset = self.instance.country.city_set.order_by('model_vehicle')

  def clean_plate(self):
    plate = self.cleaned_data['plate']
    val = validators.RegexValidator(regex='^[A-Z]{3}-[0-9]{4}$', message ="Placa no valida! intente nuevamente")
    val(plate)
    return plate

care_backend/vehicle/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from vehicle.models import Vehicle,Brand, Model
from vehicle.forms import VehicleUpdateForm, VehicleCreateForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from bootstrap_modal_forms.generic import (BSModalCreateView,
                                           BSModalUpdateView,
                                           BSModalReadView,
                                           BSModalDeleteView)
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from api.decorators import admin_required
# Create your views here.


# VEHICLE
@method_decorator([login_required,admin_required], name='dispatch')
class VehicleListView(ListView):
  model = Vehicle
  template_name = 'vehicle/vehicle_list.html'
  paginate_by = 10

@method_decorator([login_required,admin_required], name='dispatch')
class VehicleCreateView(CreateView):
  model = Vehicle
  template_name = 'vehicle/vehicle_create.html'
  form_class = VehicleCreateForm
  def form_valid(self,form):
    self.object = form.save(commit=False)
    self.object.save()
    return HttpResponseRedirect(reverse_lazy('vehiculo'))

@method_decorator([login_required,admin_required], name='dispatch')
class VehicleDetailView(BSModalReadView):
  model = Vehicle  
  template_name = 'vehicle/vehicle_detail.html'

@method_decorator([login_required,admin_required], name='dispatch')
class VehicleUpdateView(BSModalUpdateView):
  model = Vehicle
  template_name = 'vehicle/vehicle_update.html'
  form_class = VehicleUpdateForm
  success_message = 'Éxito: Vehículo actualizado.'
  success_url = reverse_lazy('vehiculo')

@method_decorator([login_required,admin_required], name='dispatch')
class VehicleDeleteView(BSModalDeleteView):
    model = Vehicle
    template_name = 'vehicle/vehicle_delete.html'
    success_message = 'Éxito: Vehículo eliminado.'
    success_url = reverse_lazy('vehiculo')

#Functions
def load_models(request):
    brand_id = request.GET.get('brand')
    models = Model.objects.filter(brand_id=brand_id).order_by('model')
    return render(request, 'vehicle/model_dropdown_list_options.html', {'models': models})

care_backend/vehicle/templates/vehicle/model_dropdown_list_options.html
<option value="">---------</option>
{% for model in models %}
<option value="{{ model.pk }}">{{ model.model }}</option>
{% endfor %}

care_backend/vehicle/templates/vehicle/vehicle_create.html
{% extends 'core/navs.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content1 %}
{% comment %} {% include 'resource/includes/resource_menu.html' %} {% endcomment %}

{% comment %} {% load i18n %}
        
{% block head %}
{{ wizard.form.media }}
{% endblock %} {% endcomment %}

<div class="container-fluid" style="background-color: #FFFFFF !important;">
  <div class="container">
    <div class="justify-content-center">
      
      <form action="" id="vehicleForm" enctype="multipart/form-data" method="post" data-models-url="{% url 'ajax_load_models' %}" novalidate>
          {% csrf_token %}
          <div class="{% if form.non_field_errors %}invalid{% endif %} ">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
          </div>
          <div class="pt-4 pb-4">
            <label style="font-size: 22px;" class="text-secondary">REGISTRAR NUEVO VEHÍCULO</label>
          </div>
          
          <div class="col-md">
            <div class="row">
              <div class='col-md-6 pt-2'>

                <label class="text-secondary pl-2" style="font-size: 14px;">Marca</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.brand class="form-control" placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Modelo</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.model class="form-control" placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Placa</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.plate class="form-control" placeholder=field.label %} 
                  </div>
                  <div class="{% if field.errors %} invalid{% endif %}">
                      <p class="help-block">{{ form.errors.plate }} </p>
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Color</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.color class="form-control" placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 13px;">Año</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                      {% render_field form.year class="form-control" placeholder=field.label %}
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Propietario</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.owner class="form-control" placeholder=field.label %} 
                  </div>
                </div>
              </div>

              <div class='col-md-6 pt-2'>
                <label class="text-secondary pl-2" style="font-size: 14px;">Descripción</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.description class="form-control" placeholder=field.label %} 
                  </div>
                </div>
                <label class="text-secondary pl-2" style="font-size: 14px;">Kilometros</label>
                <div class="col-md-7 form-group">
                  <div class="border rounded">
                    {% render_field form.km class="form-control" placeholder=field.label %} 
                  </div>
                </div>
                
                
              </div>
            </div>
          </div>
          <div class="col-md-3 pl-0 pb-3 pt-4" style="margin-left: 300px;">
            <div class="pl-0">
              <input type="submit" class="btn btn-outline-light btn-block" style="background-color: #b24f37;" value="Guardar" />
            </div>
          </div>
        </form> 

    </div>
  </div>
</div>

<script>
  $("#id_brand").change(function () {
    var url = $("#vehicleForm").attr("data-models-url");  // get the url of the `load_cities` view
    var brandId = $(this).val();  // get the selected country ID from the HTML input

    $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
      data: {
        'brand': brandId       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
        $("#id_model").html(data);  // replace the contents of the city input with the data that came from the server
      }
    });
  });
</script>

{% endblock %}

care_backend/vehicle/templates/vehicle/vehicle_delete.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Eliminar Vehículo</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">¿Seguro deseas eliminar el vehículo con placa 
      <strong>{{ object.plate }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="delete-btn btn btn-danger">Eliminar</button>
  </div>

</form>

care_backend/vehicle/templates/vehicle/vehicle_detail.html
{% load widget_tweaks %}
{% load static %}


<div class="modal-header">
  <h3 class="modal-title">Detalle de Vehículo</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <div class="mt-4 mb-4 ml-4 mr-4">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-auto">
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Marca:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.brand }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Modelo:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label  style="font-size: 14px;">{{ object.model }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" class="text-secondary" style="font-size: 14px;">Placa:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.plate }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Color:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.color }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Año:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;"> {{ object.year }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Descripción:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label  style="font-size: 14px;">{{ object.description }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">KM:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.km }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Fecha de creación:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label  style="font-size: 14px;">{{ object.created }}</label>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-auto">
              <label class="text-secondary" style="font-size: 14px;">Fecha de actualización:</label>
            </div>
            <div class="col-lg-6 col-md-auto">
              <label style="font-size: 14px;">{{ object.updated }}</label>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

care_backend/vehicle/templates/vehicle/vehicle_update.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Actualizar Vehículo</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          <p class="help-block">{{ field.errors }}</p>
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Actualizar</button>
  </div>

</form>